apiVersion: v1
kind: Service
metadata:
  name: swapi-service
spec:
  type: ExternalName
  externalName: swapi.dev
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443