apiVersion: v1
kind: Service
metadata:
  name: cassandra-service
spec:
  selector:
    app: cassandradb
  ports:
  - port: 7000
    targetPort: 7000
    name: internode-comunication
  - port: 9042
    targetPort: 9042
    name: native-clients
  type: ClusterIP